@startuml Mahasiswa2

class Mahasiswa {
  -nama: String
  -nim: String
  -usia: int
  -jurusan: Jurusan
  +Mahasiswa(nama: String, nim: String, usia: int, jurusan: Jurusan)
  +getNama(): String
  +setNama(nama: String): void
  +getNim(): String
  +setNim(nim: String): void
  +getUsia(): int
  +setUsia(usia: int): void
  +getJurusan(): Jurusan
  +setJurusan(jurusan: Jurusan): void
  +displayInfo(): void
}

class Jurusan {
  -nama: String
  -kode: String
  +Jurusan(nama: String, kode: String)
  +getNama(): String
  +setNama(nama: String): void
  +getKode(): String
  +setKode(kode: String): void
  +displayInfo(): void
}

Mahasiswa "1" -- "1" Jurusan : has >

@enduml