@startuml AlatTulis

class AlatTulis {
  - nama : String
  - stok : int
  - hargaSatuan : int
  + setNama(nama: String)
  + setStok(stok: int)
  + setHargaSatuan(hargaSatuan: int)
  + getNama(): String
  + getStok(): int
  + getHargaSatuan(): int
  + hitungHarga(): int
  + tampilkanDetail(): void
}

class Main {
  + main(args: String[]): void
}

hide empty members
hide circle
@enduml