@startuml Perpustakaan
class Perpustakaan {
    -ArrayList<Buku> daftarBuku
    +tambahBuku(Buku buku)
    +pinjamBuku(String judul, String peminjam)
    +kembalikanBuku(String judul, String peminjam)
    +tampilkanBuku()
}

class Buku {
    -String judul
    -String penulis
    -int stok
    -String peminjam
    +Buku(String judul, String penulis, int stok)
    +getters()
    +setters()
}

Perpustakaan "1" -- "*" Buku
@enduml